sudo: required
language: bash
services:
  - docker

env:
  global:
    - secure: YHWXu1mdWHUO93CrdmN9x91xhlGOLVX6QCdYiRdSaqZC2TcCUhn+BZo34vajGymYAHeNSG6+EqdY0yzJjaNUBNaxQIOWamagoZsRfWPyj0FPUnrVsm770j1W+SVDn1L+6Uq6fEwo8QRaWU8qf8tfR3T/2PIfmRyR5a1G/+w+uYkmP21afIzjHbFyCJ+KX8PAc+423BiWqde1j5Ujx2GhyaXx6UKy1WafQSZgyh6ckMTWG1gyGjkbHysMib59GNwVsOt0YDJBzFipd4cZo1qDf/TtKjjkWw6VQP8Lasa8yoeLTfoRRtHmVC3mVm+60/JfIBgzXAMHQSgKQOZu6eb8/Bck6OXY1MiXPLOlHgx4RtpylclstXZP+9451izjj7yWPkw6Il3KdVaI8yMkZrhMnuwpEnwFOEmCU1MLV+orkOrwPZ6FyF1W50xVH70PL+Bg3PhEB8sqiQkoiOjucWrgonb9y5exAZr+EXgKed7pOu6VybR4GArAq6A7xPA/v/SNBrvAEuKY5T/QiO4nXkm2FF5Zh2+t5UCHC4fnuQLhojnlhN9pGV4qQT8xNbg3r1wigRrAIGeiGvGnI5WwmzUhYJMDnHbA3DyOuzy22+8Xh0quiHnOI+9jz6TONCD0fPQg5FJUaxWcj8bWJtentlDqClJFw1JJaiHtWqSl35wfj7I=
    - COMMIT_AUTHOR_MAIL: "doc-team@suse.com"

before_install:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
  # a. The `sed` below tries to make sure commit messages use a safe subset
  #    of characters that Bash won't randomly interpret. Temporarily enabling
  #   `set -f` (disables globbing) might also be an option but not sure that
  #    globbing is our only problem. Maybe there would be other issues.
  # b. Note the position of ] and - in the character class. This is the only
  #    way to combine those two characters in a regex.
  - echo "TRAVIS_COMMIT_MESSAGE='"$(echo "$TRAVIS_COMMIT_MESSAGE" | sed -r 's/[^][() _0-9a-z-]/_/g')"'" >> env.list
  - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
  - ls
  - echo "Building docker image"
  - docker build -t sle-doc-image .

script:
  - docker run --rm -it sle-doc-image /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: change
